#!/bin/bash


set -x
set -e


root="$1"

user="$2"

state="$3"

done_file="${state}/done"
log_file="${state}/log"

echo "Starting $0." >> "${log_file}"
echo "Done: ${done_file}" >> "${log_file}"
echo " Log: ${log_file}" >> "${log_file}"

while true
do
    ./walk-or-resume "${root}" "${state}" | ./upload-or-update "${user}" "${log_file}" "${done_file}"
    echo "Sleeping.." >> "${log_file}"
    sleep 15m
done
echo "Exiting $0." >> "${log_file}"
